services:

  db:
    image: postgres:16-alpine 
    restart: always
    environment:
      POSTGRES_USER: devuser      
      POSTGRES_PASSWORD: devpassword 
      POSTGRES_DB: travelhub_db    
    ports:
      - '5433:5432'               
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: